### ISSUE TITLE
websocket.ReceiveAsync cannot be cast to WebSocketReceiveAsync

### ISSUE THREAD

**Issue by Que8549** [learncode/NoteApp#1]
Hello,

Thanks for the app! I'm having an issue trying to get it to run though. I get this error:

WebSocket connection to failed: Error during WebSocket handshake: 'Sec-WebSocket-Protocol' header value '' in response does not match any of sent values

When I debug through the app the WebSocketEcho method returns abruptly when it hits this line:

var wsRecieveAsync = (WebSocketReceiveAsync)wsEnv["websocket.ReceiveAsync"];

It looks like the code is unable to cast wsEnv["websocket.ReceiveAsync"] to type of WebSocketReceiveAsync, but wsEnv["websocket.ReceiveAsync"]  has this value:

{[websocket.ReceiveAsync, System.Func`3[System.ArraySegment`1[System.Byte],System.Threading.CancellationToken,System.Threading.Tasks.Task`1[System.Tuple`3[System.Int32,System.Boolean,System.Int32]]]]}

Any ideas on how I can fix this?

**Comment by Que8549** [comment]
I was able to resolve the error. The problem is that the Delegate Signatures have changed. I changed the Delegate Signatures to those I found below and was able to get everything working
http://owin.org/spec/extensions/owin-WebSocket-Extension-v0.4.0.htm

**Comment by learncode** [comment]
@Que8549 apologies for the delayed reply. Thank you for the find, can you create a pull request I can merge the code.
